### PR TITLE
feat: ➕ try instantiation expression from custom TS build 📦

### PR DESCRIPTION
**Pull request by Beraliv**
Build from PR comment – https://github.com/microsoft/TypeScript/pull/47607#issuecomment-1023370466

Playground (will be updated 🔄):

1. Initial state – https://tsplay.dev/w2451m (we have `fivePagesInCategoryTen: any` here – https://tsplay.dev/NBjJdN)

### CODE REVIEW

**Comment by Beraliv** [comment]
@ai 

Probably we already discussed it (correct me if I'm wrong) but I found a solution to fix `any` when you combine params and count (even for old TypeScript version): https://tsplay.dev/mbAE2N

Do I need to fix it separately?

**Comment by ai** [comment]
Let’s try this fix in this PR (since it is a main reason to try new TS version)

**Comment by Beraliv** [comment]
@ai here I check other possibilities here

I decided to move changes that are not connected with new TypeScript possibilities to https://github.com/nanostores/i18n/pull/13

**Comment by ai** [comment]
https://github.com/nanostores/i18n/pull/13 looks great too. I am waiting for test fix there and I am ready to merge,

**Comment by Beraliv** [comment]
Btw, it was merged 11 hours ago 🚀 and will be available in TypeScript@4.7

**Comment by ai** [comment]
Am I right that we can close it?

**Comment by Beraliv** [comment]
> Am I right that we can close it?

Sorry for the late response, yeah, let's close it for now

**Pull request closed without merging**
